spring:
  datasource:
    url: jdbc:${WORKOUT_DB_NAME}
    username: ${WORKOUT_DB_USER}
    password: ${WORKOUT_DB_SECRET_KEY}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
    generate-ddl: true